name: OpenType docs feedback template.
description: |
  ⛔ This template is hooked into the feedback control on the bottom of pages on the learn.microsoft.com site. It automatically fills in several fields for you. Don't use for other purposes. ⛔
labels:
  - "OpenType spec"
body:
  - type: markdown
    attributes:
      value: "## Issue information"
  - type: markdown
    attributes:
      value: Describe the issue in the text box below. Add as much detail as needed to help us resolve the issue.
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Description
  - type: markdown
    attributes:
      value: "## 🚧 Article information 🚧"
  - type: markdown
    attributes:
      value: "*Don't modify the following fields*. They are automatically filled in for you. Doing so will disconnect your issue from the affected article. *Don't edit them*."
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
